language: java
jdk:
  - oraclejdk8

sudo: required
services:
    - docker

cache:
    directories:
        - '$HOME/.m2'

install:
    - mvn clean install -DskipTests

jobs:
    include:
       - stage: test
         script: mvn clean install

