redis:
    image: redis
    ports: 
        - "6379:6379"
postgres:
    image: postgres
    environment:
      - POSTGRES_USER:'postgres'
      - POSTGRES_PASSWORD:'postgres'
      - POSTGRES_DB:'containerized'
    ports:
        - "5432:5432"
